name: Latest Medium blog posts
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day at 12 am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest medium blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@giorgiosaud"
          feed_names: "Medium"
          committer_email: "giorgiosaud@gmail.com"
          committer_username: "giorgiosaud"
          max_post_count: 50
          comment_tag_name: "MEDIUM-BLOG-POST-LIST"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
